#%RAML 1.0
title: SGST Audit PAPI
description: Process API to publish the files to common storage system.
        
traits:  
  pcsHeaders: !include trait-pcs-headers.raml

uses:
  dataTypesLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/datatypes-library/1.0.1/datatypes-library.raml
  traitsLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/traits-library/1.0.1/traits-library.raml
  resourceTypesLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/resource-types-library/1.0.1/library-resource-types.raml
  securitySchemesLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/security-schemes-library/1.0.0/library-security-schemes.raml


#securitySchemes: securitySchemesLib.basicAuthentication

/backup:
  post:
    is: 
      - traitsLib.hasCorrelationID
      - pcsHeaders
    body:
      multipart/form-data:
        type: file

