#%RAML 1.0 Trait
headers: 
  fileName:
    type: string
    required: true
    example: BOM
    description: File Name 
  fileType:
    type: string
    required: true
    example: vendor-master
    description: Type of file
  direction:
    type: string
    required: true
    example: outbound
    description: direction of the flow
  externalSystem:
    type: string
    required: true
    example: SCM
    description: source system
  fileExtension:
    type: string
    required: true
    example: csv
    description: target system
  correlationID:
    type: string
    required: true
  