#%RAML 1.0 Trait
headers: 


  direction:
    type: string
    required: true
    description: Direction of transaction inbound/outbound
  externalSystem:
    type: string
    required: true
    description: External System involved in the transaction
  correlationID: 
    type: string
    required: true
    description: Unique transaction ID
  fileExtension:
    type: string
    required: true
    description: Extension of file
  fileType:
    type: string
    required: true
    description: Type of the file e.g., purchase-orders
  fileName:
    type: string
    required: true
    description: Name of the file 
  
  